[build]
  publish = "build"
  command = "yarn build"

[build.environment]
  NODE_VERSION = "20"
  YARN_VERSION = "1.22.22"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true
